import requests, json

endpoint = 'https://oai-rfq-automation-01.openai.azure.com/openai/deployments/gpt-5/chat/completions?api-version=2024-02-01'
headers = {
    'api-key': 'YOUR_AZURE_OPENAI_KEY_HERE',
    'Content-Type': 'application/json'
}

prompt = """You are an AI assistant that processes Requests for Quotation (RFQ). Your ONLY output must be a valid JSON object. Do NOT output any plain text, markdown, or explanation outside the JSON.

STEP 1 - CLASSIFY: Determine if the email is a genuine RFQ or spam/newsletter. Set is_rfq accordingly.

STEP 2 - EXTRACT: Extract customer_name, contact_email, confidence_score (0.0 to 1.0), and reasoning.

STEP 3 - MATCH ITEMS: Use this catalog to match requested items and calculate prices:
- SKU: VALVE-SS-2IN | Industrial Valve 2-inch Stainless | $120.00 | 7 Business Days
- SKU: SENSOR-PRESS-DIG | High-Pressure Digital Sensor | $350.00 | 14 Business Days
- SKU: FLOW-MTR-EM-4IN | Flow Meter Electromagnetic 4-inch | $850.00 | 21 Business Days
- SKU: PUMP-CENT-5HP | Centrifugal Pump 5HP | $1,450.00 | 28 Business Days
- SKU: GSKT-FLG-2IN | Flange Gasket Kit 2-inch | $25.00 | 7 Business Days
For unmatched items: unit_price = 0, lead_time = TBD.

STEP 4 - BUILD HTML EMAIL: Set draft_email_html to EXACTLY this HTML structure (fill in the dynamic values, do not change the HTML/CSS structure):

"<div style='font-family:Arial,Helvetica,sans-serif;max-width:700px;margin:0 auto;color:#333;'><div style='background:#1a3c5e;padding:20px 30px;'><h1 style='color:#ffffff;margin:0;font-size:22px;'>VSO Zimbabwe - Formal Quotation Proposal</h1><p style='color:#a8c8e8;margin:5px 0 0;font-size:13px;'>Reference: RFQ-AUTO | Date: [TODAY DATE]</p></div><div style='padding:25px 30px;background:#ffffff;'><p style='font-size:15px;'>Dear [CUSTOMER NAME],</p><p style='font-size:14px;line-height:1.6;'>Thank you for reaching out with your Request for Quotation. Below is our formal pricing proposal for your requested items:</p><table style='width:100%;border-collapse:collapse;margin:20px 0;font-size:14px;'><thead><tr style='background:#1a3c5e;color:#ffffff;'><th style='padding:12px 15px;text-align:left;border:1px solid #ddd;'>Item &amp; SKU</th><th style='padding:12px 15px;text-align:center;border:1px solid #ddd;'>Qty</th><th style='padding:12px 15px;text-align:right;border:1px solid #ddd;'>Unit Price</th><th style='padding:12px 15px;text-align:right;border:1px solid #ddd;'>Total Price</th><th style='padding:12px 15px;text-align:center;border:1px solid #ddd;'>Lead Time</th></tr></thead><tbody>[TABLE ROWS - one TR per line item: odd rows background #f8f9fa, even rows background #ffffff. Each TD uses padding:10px 15px;border:1px solid #ddd. Item column shows Name then SKU in smaller grey text. Qty centered. Unit Price and Total Price right-aligned with $ prefix.]</tbody><tfoot><tr style='background:#e8f0e8;font-weight:bold;'><td colspan='3' style='padding:12px 15px;border:1px solid #ddd;text-align:right;'>Total Quoted Amount (USD):</td><td style='padding:12px 15px;border:1px solid #ddd;text-align:right;font-size:16px;color:#1a3c5e;'>$[GRAND TOTAL]</td><td style='padding:12px 15px;border:1px solid #ddd;'></td></tr></tfoot></table><div style='background:#f0f7ff;border-left:4px solid #1a3c5e;padding:15px 20px;margin:20px 0;font-size:13px;'><p style='margin:0 0 8px;'><strong>Quotation Terms:</strong></p><p style='margin:0;'>This quotation is valid for <strong>30 days</strong> from the date above. Prices are in USD. Lead times are estimates from order confirmation. To proceed, please reply to this email with your official Purchase Order.</p></div><p style='font-size:14px;margin-top:20px;'>Best regards,<br/><strong>Commercial Sales Team</strong><br/>VSO Zimbabwe<br/><a href='mailto:martin.kuda@gmail.com' style='color:#1a3c5e;'>martin.kuda@gmail.com</a></p></div><div style='background:#f5f5f5;padding:12px 30px;text-align:center;font-size:11px;color:#888;'>This is an automated quotation generated by VSO Zimbabwe RFQ System. &copy; 2025 VSO Zimbabwe.</div></div>"

RETURN this exact JSON structure:
{"is_rfq": boolean, "customer_name": string, "contact_email": string, "confidence_score": number, "reasoning": string, "quote_total": number, "draft_email_html": string, "line_items": [{"sku": string, "name": string, "quantity": integer, "unit_price": number, "line_total": number, "lead_time": string}]}"""

email = """
Forwarded message:
From: Someone
To: martin.kuda@gmail.com
Subject: [External] Fwd: Quote for Industrial Valve

Hi, let's catch up later!
"""

payload = {
    'messages': [
        {'role': 'system', 'content': prompt},
        {'role': 'user', 'content': email}
    ],
    'response_format': { 'type': 'json_object' }
}

try:
    r = requests.post(endpoint, headers=headers, json=payload)
    print("Status:", r.status_code)
    try:
        content = r.json()['choices'][0]['message']['content']
        print("Raw Content:", content)
        parsed = json.loads(content)
        print("is_rfq:", parsed.get('is_rfq'), "type:", type(parsed.get('is_rfq')))
        print("confidence_score:", parsed.get('confidence_score'), "type:", type(parsed.get('confidence_score')))
    except Exception as je:
        print("Failed to parse JSON response:", je)
        print("Raw:", r.text)
except Exception as e:
    print(e)
